@LogiTechAPI_HostAddress = http://localhost:5085

GET {{LogiTechAPI_HostAddress}}/api/kargo/saglik
Accept: application/json

###

POST {{LogiTechAPI_HostAddress}}/api/kargo/hesapla
Content-Type: application/json

{
  "paketTipi": "Standart",
  "ekstralar": [],
  "tasimaYolu": "Karayolu"
}

###
